// <auto-generated />
using System;
using Intex.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intex.API.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406202804_InitialApp")]
    partial class InitialApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Intex.API.Models.CaseConference", b =>
                {
                    b.Property<int>("ConferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ConferenceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decisions")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilitatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextSteps")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConferenceId");

                    b.HasIndex("ResidentId");

                    b.ToTable("case_conferences", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByPartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DonationId");

                    b.HasIndex("CreatedByPartnerId");

                    b.HasIndex("ReferralPostId");

                    b.HasIndex("SupporterId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountAllocated")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttendanceRate")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GpaLikeScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Bmi")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DentalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EnergyScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MedicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicalNotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NutritionScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PsychologicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SleepScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SafetyConcernsNoted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedUnitValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AssignmentStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.PredictionResult", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureImportanceJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PredictionId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SupporterId");

                    b.ToTable("prediction_results", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfAdmission")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyIs4Ps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("PwdType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidentId");

                    b.HasIndex("CaseControlNo")
                        .IsUnique();

                    b.HasIndex("SafehouseId");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityGirls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityStaff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveResidents")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgEducationProgress")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgHealthScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeVisitationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("MonthEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessRecordingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaptionLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickThroughs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationReferrals")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EngagementRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedDonationValuePhp")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeaturesResidentStory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Forwards")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCallToAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hashtags")
                        .HasColumnType("TEXT");

                    b.Property<int>("Impressions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<int>("MentionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumHashtags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileVisits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.SupporterUserLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LinkId");

                    b.HasIndex("SupporterId", "UserId")
                        .IsUnique();

                    b.ToTable("supporter_user_links", (string)null);
                });

            modelBuilder.Entity("Intex.API.Models.CaseConference", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("CaseConferences")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex.API.Models.Donation", b =>
                {
                    b.HasOne("Intex.API.Models.Partner", "CreatedByPartner")
                        .WithMany("ReferredDonations")
                        .HasForeignKey("CreatedByPartnerId");

                    b.HasOne("Intex.API.Models.SocialMediaPost", "ReferralPost")
                        .WithMany("ReferredDonations")
                        .HasForeignKey("ReferralPostId");

                    b.HasOne("Intex.API.Models.Supporter", "Supporter")
                        .WithMany("Donations")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByPartner");

                    b.Navigation("ReferralPost");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Intex.API.Models.DonationAllocation", b =>
                {
                    b.HasOne("Intex.API.Models.Donation", "Donation")
                        .WithMany("Allocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intex.API.Models.Safehouse", "Safehouse")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex.API.Models.EducationRecord", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("EducationRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex.API.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("HealthRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex.API.Models.HomeVisitation", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("HomeVisitations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex.API.Models.InKindDonationItem", b =>
                {
                    b.HasOne("Intex.API.Models.Donation", "Donation")
                        .WithMany("Items")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Intex.API.Models.IncidentReport", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("IncidentReports")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intex.API.Models.Safehouse", "Safehouse")
                        .WithMany("IncidentReports")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex.API.Models.InterventionPlan", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex.API.Models.PartnerAssignment", b =>
                {
                    b.HasOne("Intex.API.Models.Partner", "Partner")
                        .WithMany("Assignments")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intex.API.Models.Safehouse", "Safehouse")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("SafehouseId");

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex.API.Models.PredictionResult", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("PredictionResults")
                        .HasForeignKey("ResidentId");

                    b.HasOne("Intex.API.Models.Supporter", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterId");

                    b.Navigation("Resident");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Intex.API.Models.ProcessRecording", b =>
                {
                    b.HasOne("Intex.API.Models.Resident", "Resident")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex.API.Models.Resident", b =>
                {
                    b.HasOne("Intex.API.Models.Safehouse", "Safehouse")
                        .WithMany("Residents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex.API.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("Intex.API.Models.Safehouse", "Safehouse")
                        .WithMany("MonthlyMetrics")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex.API.Models.SupporterUserLink", b =>
                {
                    b.HasOne("Intex.API.Models.Supporter", "Supporter")
                        .WithMany("UserLinks")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Intex.API.Models.Donation", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Intex.API.Models.Partner", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ReferredDonations");
                });

            modelBuilder.Entity("Intex.API.Models.Resident", b =>
                {
                    b.Navigation("CaseConferences");

                    b.Navigation("EducationRecords");

                    b.Navigation("HealthRecords");

                    b.Navigation("HomeVisitations");

                    b.Navigation("IncidentReports");

                    b.Navigation("InterventionPlans");

                    b.Navigation("PredictionResults");

                    b.Navigation("ProcessRecordings");
                });

            modelBuilder.Entity("Intex.API.Models.Safehouse", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("IncidentReports");

                    b.Navigation("MonthlyMetrics");

                    b.Navigation("PartnerAssignments");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("Intex.API.Models.SocialMediaPost", b =>
                {
                    b.Navigation("ReferredDonations");
                });

            modelBuilder.Entity("Intex.API.Models.Supporter", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("UserLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
